import 'index.html';
import '__map-preview-screen.html';
import 'assets/stylesheets/styles.scss';
import 'assets/images/favicon.png';
import 'assets/images/map_unknown.jpg';
import 'assets/images/map_robotic_sword.jpg';
import 'assets/images/map_robo_bay.jpg';
import 'assets/images/map_stairs_of_steel.jpg';
import 'assets/images/map_closed_circuit.jpg';
